<cms:show_early>
<html>
  <head>
    <title><cms:date format='H:i:s' /></title>

    <!-- CSS file -->
    <!-- Additional CSS Themes file -->

    <!-- Using jQuery with a CDN -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>

    <!-- JS file -->
  </head>
  Head loaded..<br/>
</cms:show_early>
  <cms:pages/>
  <cms:show_early>First pages tag finished..<br/></cms:show_early>
  <cms:pages/>
  <cms:show_early>Second pages tag finished..<br/></cms:show_early>
  <cms:pages/>
  <cms:show_early>Third pages tag finished..<br/></cms:show_early>
</html>
